### ISSUE TITLE
Cli not useable with cronjob when $USER is missing

### ISSUE THREAD

**Issue by pm-pm** [gotify/cli#13]
The CLI for Linux (amd64 and 386) make an error when running **within a cronjob**. Running from shell does not make any errors. From my point it is the missing environment problem?

This is not working:
```
#!/bin/bash
/opt/gotify-cli-linux-amd64 p -p 1 --url "http://localhost:8080" --token "Axxxxxxxxxxxxxx" -t "Cron Demo" "via Cronjob"
```
This error is occur:
```
user: Current not implemented on linux/amd64
or
user: Current not implemented on linux/386
```
You can solve the problem with an USER  line:
```
#!/bin/bash

export USER=dummy

/opt/gotify-cli-linux-amd64 p -p 1 --url "http://localhost:8080" --token "Axxxxxxxxxxxxxx" -t "Cron Demo" "via Cronjob"
```
It does NOT matter which username you add. "dummy" or "root" or "something" is ok.

PS: A note:  In my mind there was also am issue with $HOME variable. But in my tests from today $HOME is not needed.

**Comment by eternal-flame-AD** [comment]
I think we should just skip reading the config file from user directory if it cannot be determined instead of exit with failure. @jmattheis

**Comment by jmattheis** [comment]
:+1:
