### ISSUE TITLE
How to insert newlines into text?

### ISSUE THREAD

**Issue by bj73** [gotify/cli#15]
Hi, is it possible to insert newline characters into the text that is sent?

I've tried inserting \n in the text - result is it just gets output, eg. gotify push -t "Test" -p 5 "fred\nnurk" gives: fred\nnurk

Also tried setting a variable as newline, eg. nl=$'\n', but this gets transformed into a space, eg. gotify push -t "Test" -p 5 "fred${nl}nurk" gives: fred nurk

TIA

**Comment by eternal-flame-AD** [comment]
See [https://github.com/gotify/android/issues/65].

**Comment by bj73** [comment]
Ah OK, thanks for that.

**Comment by adameus03** [comment]
The link is dead now :(

**Comment by jmattheis** [comment]
@adameus03 you can use `\n` or literal newlines:
```
$ gotify push 'hello\nworld'
```
```
$ gotify push "hello
world"
