### ISSUE TITLE
Support watching command output

### ISSUE THREAD

**Issue by eternal-flame-AD** [gotify/cli#19]
I think it would be good if we can support watching changes of command output and sending the difference to gotify, similar to the `watch` command in *nix.

Then, when we want to do something really simple such as  watching a change to the return of an api, we can simply do:
```bash
$ gotify-cli watch 'curl http://api.example.com/some_data | jq ".something_interesting"'
```

And them gotify would keep polling the data and send a notification when the output changes.

**Comment by jmattheis** [comment]
Yeah, pretty good idea!

**Comment by eternal-flame-AD** [comment]
Okay, I will open a PR for this
