### ISSUE TITLE
Update config location to use XDG standard

### ISSUE THREAD

**Issue by StewartThomson** [gotify/cli#31]
The CLI should place its configuration file according to the XDG Specification.

See here for more details on the XDG Specification: https://wiki.archlinux.org/index.php/XDG_Base_Directory

If we're okay with the dependency, https://github.com/adrg/xdg looks good & robust for handling this cross-platform.

Let me know if you're interested, and I'll get to work on it.

**Comment by jmattheis** [comment]
This would be ok, as long as old config paths will still be supported.
