### ISSUE TITLE
Default priority set in cli.json is ignored

### ISSUE THREAD

**Issue by amo13** [gotify/cli#36]
`/etc/gotify/cli.json`
```
{
  "token": "XXXXXXXXXXXXXXX",
  "url": "http://127.0.0.1:8057",
  "defaultPriority": 10
}
```

When I call `gotify-cli push -t "title" "message"`, the notification successfully gets pushed and received, but the priority is 0.
I restarted the server (`systemctl restart gotify-server`) to hopefully make it re-read the config file, but it makes no difference. `/etc/gotify/cli.json` is the only config file I have.

`gotify/server v2.0.18 (archlinux)`
`gotify/cli v2.1.1 (archlinux)`

**Comment by jmattheis** [comment]
Looks like the version isn't released yet, so you still use a version that doesn't include the defaultPriority addition.

**Comment by amo13** [comment]
#34 found it! Thank you for the hint!
