### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by amo13** [gotify/cli#37]
Dear gotify devs,

I appreciate a lot this CLI for gotify and already integrated it for multiple purposes on two servers. I'd love to use the configuration option for the default notification priority, which is not yet available (or fixed) in the current release.
Can you please publish a new release with binaries of the current master so people can receive this feature through the package managers of their OS?
For reference, the need for a new release was mentioned in #36.

Thank you!

**Comment by jmattheis** [comment]
Sure thing -> https://github.com/gotify/cli/releases/tag/v2.2.0

**Comment by amo13** [comment]
Amazing, thank you a lot!
