### ISSUE TITLE
Add `GOTIFY_SKIP_VERIFY_TLS` option to the config file

### ISSUE THREAD

**Issue by egvimo** [gotify/cli#49]
Would it be possible to add the `GOTIFY_SKIP_VERIFY_TLS` flag to the configuration file?

```json
{
  "token": "A4ZudDRdLT40L5X",
  "url": "https://gotify.example.com",
  "defaultPriority": 6
  "skipVerifyTls": true
}
```

This way the whole configuration would reside in one place.

**Comment by jmattheis** [comment]
This is by design https://github.com/gotify/cli/issues/27#issuecomment-500094180 if you want to permanently an insecure certificate then you should trust it locally.

**Comment by egvimo** [comment]
I understand that. But there are some motivations for my request and maybe you change your mind and add this option. Let me explain:

- This option is also available in the (Android) App
- Gotify is a self hosted solution, so I think many (like me) use it in a private network without a valid certificate from a CA
- The environment variable can also be configured globally to be persistent
- Using `https` and skipping the TLS Verification is better than using plan `http`

It's just **much more convenient**, **more transparent** and **less error-prone** to have all configuration in one place.
