### ISSUE TITLE
Example of sending image via CLI

### ISSUE THREAD

**Issue by BilalBhatti** [gotify/cli#51]
Hello, is it possible to send images via gotify cli?

Assuming config file exists.

`gotify push --contentType "text/markdown" -t "Image" "https://placekitten.com/400/300"
`
Thanks?

**Comment by jmattheis** [comment]
Use markdown image syntax: https://www.markdownguide.org/basic-syntax/#images-1

**Comment by BilalBhatti** [comment]
> Use markdown image syntax: https://www.markdownguide.org/basic-syntax/#images-1

`gotify push --contentType "text/markdown" -t "Image" "![sample alt text](/var/www/html/images/test.jpg)"`

gets error `-bash: ![alt: event not found`

**Comment by BilalBhatti** [comment]
Never mind. Managed to send it this time. Thanks

**Comment by jmattheis** [comment]
https://gotify.net/docs/more-pushmsg#python

**Comment by jmattheis** [comment]
please read the docs, it needs to be nested into extras https://gotify.net/docs/msgextras#clientdisplay
```
resp = requests.post('http://localhost:8080/message?token=A51DTcEH99U2mOq', json={
    "message": "[![Tap to view image](https://placekitten.com/400/300)](https://placekitten.com/400/300)",
    "priority": 10,
    "title": "Testing markdown"
    "extras": {
         "client::display": {
             "contentType": "text/markdown"
         }
    }
})
```

**Comment by BilalBhatti** [comment]
> [![alt text for screen readers](/var/www/html/images/test.jpg)]

But is it possible to send image and a big picture as well for notification at the same time? It do not work as it does enable big picture in notification but at the same time disables markdown

```
def send_image(title, priority, url):
    resp = requests.post('http://localhost:8080/message?token=AAPIs8g8cedVLq3', json={
        "message": "[![Tap to view image]("+url+")]("+url+")",
        "priority": priority,
        "title": title,
        "extras": {
              "client::notification": {
                 "bigImageUrl": url
             }
        }
    })
    print (resp)
```

**Comment by jmattheis** [comment]
You need to put both the "client::notification" and "client::display" block into the extras.

**Comment by BilalBhatti** [comment]
@jmattheis If you can please edit out my token from your 2nd last reply, I would be obliged :)

**Comment by BilalBhatti** [comment]
@jmattheis Sorry man!
