### ISSUE TITLE
Is there a way to run command/scripts according to the received messges?

### ISSUE THREAD

**Issue by tonyho** [gotify/cli#57]
I am curious about if there's a similar program like cli which can watching/waiting the messages, and run commands according to the received messages?

If such a tool exists, can anyone tell me, thanks?
I am hoping to use such a tool to control my raspberryPi Linux to do something according to messages.

**Comment by jmattheis** [comment]
Hey, have a look at this ticket: https://github.com/gotify/server/issues/255

**Comment by tonyho** [comment]
> Hey, have a look at this ticket: [gotify/server#255](https://github.com/gotify/server/issues/255)↳

Thanks, this gives me some thoughts. It's wonderful.
