### ISSUE TITLE
gotify watch command can not find aliases and shell functions - exit status 127

### ISSUE THREAD

**Issue by melo0187** [gotify/cli#58]
Whenever trying to use a function defined in my zshrc or a zsh alias as command for gotify-cli watch it fails:
> first run failed command failed to invoke: exit status 127

Is there any way for gotify to have access to those functions and aliases?

**Comment by jmattheis** [comment]
You can specify the shell that is used to execute the command with `--exec` or `-x`.
```
$ gotify watch -o short -x '/bin/zsh -c' 'echo $ZSH $RANDOM'
/usr/share/oh-my-zsh 14408
```

**Comment by jmattheis** [comment]
Your aliases are probably configured inside your .zshrc, `zsh -c` doesn't source that, because the shell isn't interactive:

> `$HOME/.zshrc` Used for setting user's interactive shell configuration and executing commands, will be read when starting as an interactive shell.

https://wiki.archlinux.org/title/zsh

add `-i` to the zsh command:

```
$ gotify watch -o short -x '/bin/zsh -ic' 'echo $ZSH $RANDOM'
```

**Comment by melo0187** [comment]
Ah, I didn't read the zsh documentation... my bad.
Thank you @jmattheis for explaining. Works like a charm =)
