### ISSUE TITLE
token via env var

### ISSUE THREAD

**Issue by tessus** [gotify/cli#59]
If one uses the `--token` argument, the token shows up in the process list. When I use different scripts on the same machine that use the gotify client, I'd also like to use different tokens in these scripts.

Thus it would be awesome to set a `GOTIFY_TOKEN` env var in the script and the gotify cli uses the token from the env var.

Any chance that this can be added?

P.S.: I am more than happy to create a PR. I only want to know, whether such a change would be accepted.

**Comment by jmattheis** [comment]
You can already put the token inside the configuration file, but I'd accept such an addition. The cli library that gotify uses should already support obtaining flags via env vars.

**Comment by tessus** [comment]
> You can already put the token inside the configuration file

Since I cannot use an argument to point to a config file, this approach is unfortunately useless.

How am I supposed to do that when I have 2 scripts running? Script 1 changes the config file, pushes a message, script 2 changes the config file, pushes a message, and so on?
Sounds awkward and it requires locking. Now imagine 5 scripts/applications on one machine.

> I'd accept such an addition
> The cli library that gotify uses should already support obtaining flags via env vars.

Great, I will have a look at it when I get up tomorrow. It's way past my bed time.

**Comment by tessus** [comment]
Done.
