### ISSUE TITLE
Use gotify problems:Client http 401 error

### ISSUE THREAD

**Issue by user10246** [gotify/cli#62]
Web server :ubuntu 23.04
Install method:doker
The problems is http 401 error
PS:use ip domain name

**Comment by user10246** [comment]
I use smsforwarder creat new send passage with gotify.
That is:
![Uploading IMG_20230831_221535.jpg…]()

**Comment by jmattheis** [comment]
the image link doesn't work.

**Comment by user10246** [comment]
Please wait I will found some ways to solve

**Comment by user10246** [comment]
https://mypikpak.com/s/VNdB-dvpfqATexLgDf-leP75o1
IMG_20230831_221535.jpg

**Comment by user10246** [comment]
That's ok

**Comment by user10246** [comment]
Hello, jmattheis. I'm sorry to tell you that I took up your time because of my personal configuration error. (I used Clients instead of Application)
Say sorry again for my personal wrong.
Thanks for your help!!!:p
