### ISSUE TITLE
bash implementation

### ISSUE THREAD

**Issue by RubenNL** [gotify/cli#7]
I don't know why this script/program is written in GO, so I created a bash-version of this program.

[https://github.com/RubenNL/gotify-bash](https://github.com/RubenNL/gotify-bash)

Would it be possible to have an official version based on bash? Not everyone is able to use the binaries/compile GO on his platform.

**Comment by jmattheis** [comment]
Well, I wrote the CLI in Go because I like writing Go code. 

Yeah it would be possible to have a offical bash version of the cli,

**Comment by PanderMusubi** [comment]
@RubenNL you can make a PR that lists your work in the alternatives.

**Comment by PanderMusubi** [comment]
@RubenNL can we close this as your implementation hasn't been developed further?
