### ISSUE TITLE
issue with cron

### ISSUE THREAD

**Issue by ghost** [gotify/cli#73]
Hi,
I am trying to use a working gotify-cli in cron (debian bookworm).
As a test:

1. ` crontab -e`
2. add at the end
> */2 * * * * gotify push "message"
3. `sudo systemctl restart cron`

# actual behaviour
the job is run, but no message is pushed

# additional notes
no issue if the command is replaced with curl, as stated in the readme:

`curl "https://push.example.de/message?token=<apptoken>" -F "title=my title" -F "message=my message"`

Thanks

**Comment by eternal-flame-AD** [comment]
Have to confirmed that the gotify executable actually is invoked? I don't use cron anymore but I remember they do not consider user shell PATHs so you may need to use the absolute path unless you put gotify in /usr/local/bin or something

**Comment by eternal-flame-AD** [comment]
Cron is a straight exec() environment so any user shell profiles won't be in effect, you can spawn a shell manually to get around this
